export const brandsWithModels = [
  {
    name: "Toyota",
    logoFile: "toyota.png",
    models: [
      "Corolla",
      "Camry",
      "RAV4",
      "Highlander",
      "Yaris",
      "Avensis",
      "Prius",
      "Land Cruiser",
    ],
  },
  {
    name: "Volkswagen",
    logoFile: "volkswagen.jpg",
    models: [
      "Golf",
      "Passat",
      "Tiguan",
      "Polo",
      "Jetta",
      "Touran",
      "Arteon",
      "Touareg",
      "T-Cross",
    ],
  },
  {
    name: "Ford",
    logoFile: "ford.jpg",
    models: [
      "Focus",
      "Fiesta",
      "Mustang",
      "Explorer",
      "Escape",
      "Edge",
      "Kuga",
      "Fusion",
    ],
  },
  {
    name: "Honda",
    logoFile: "honda.png",
    models: [
      "Civic",
      "Accord",
      "CR-V",
      "Jazz",
      "HR-V",
      "Insight",
      "Pilot",
      "Fit",
    ],
  },
  {
    name: "Hyundai",
    logoFile: "hyundai.png",
    models: [
      "Elantra",
      "i30",
      "Tucson",
      "Santa Fe",
      "Kona",
      "i20",
      "Accent",
      "Palisade",
    ],
  },
  {
    name: "BMW",
    logoFile: "bmw.png",
    models: [
      "1 Series",
      "3 Series",
      "5 Series",
      "X1",
      "X3",
      "X5",
      "X6",
      "7 Series",
    ],
  },
  {
    name: "Mercedes-Benz",
    logoFile: "mercedes.png",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "E-Class",
      "GLA",
      "GLC",
      "GLE",
      "S-Class",
    ],
  },
  {
    name: "Audi",
    logoFile: "audi.webp",
    models: ["A1", "A3", "A4", "A6", "Q2", "Q3", "Q5", "Q7"],
  },
  {
    name: "Kia",
    logoFile: "kia.jpg",
    models: [
      "Ceed",
      "Sportage",
      "Rio",
      "Sorento",
      "Picanto",
      "Niro",
      "Stinger",
      "Seltos",
    ],
  },
  {
    name: "Nissan",
    logoFile: "nissan.jpg",
    models: [
      "Qashqai",
      "Micra",
      "Juke",
      "X-Trail",
      "Leaf",
      "Navara",
      "Altima",
      "Rogue",
    ],
  },
  {
    name: "Peugeot",
    logoFile: "peugeot.png",
    models: ["208", "308", "3008", "2008", "508", "5008", "RCZ", "407"],
  },
  {
    name: "Renault",
    logoFile: "renault.jpg",
    models: [
      "Clio",
      "Megane",
      "Captur",
      "Kadjar",
      "Talisman",
      "Laguna",
      "Scenic",
      "Koleos",
    ],
  },
  {
    name: "Mazda",
    logoFile: "mazda.png",
    models: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-30", "MX-5"],
  },
  {
    name: "Škoda",
    logoFile: "skoda.png",
    models: [
      "Octavia",
      "Fabia",
      "Superb",
      "Kodiaq",
      "Kamiq",
      "Scala",
      "Roomster",
      "Yeti",
    ],
  },
  {
    name: "Volvo",
    logoFile: "volvo.png",
    models: ["S60", "S90", "V60", "XC40", "XC60", "V90", "XC90"],
  },
  {
    name: "Fiat",
    logoFile: "fiat.jpg",
    models: [
      "Panda",
      "500",
      "Tipo",
      "Punto",
      "Doblo",
      "Bravo",
      "Linea",
      "Qubo",
    ],
  },
  {
    name: "Chevrolet",
    logoFile: "chevrolet.jpg",
    models: [
      "Spark",
      "Cruze",
      "Malibu",
      "Equinox",
      "Trax",
      "Aveo",
      "Captiva",
      "Blazer",
    ],
  },
  {
    name: "Opel",
    logoFile: "opel.jpg",
    models: [
      "Corsa",
      "Astra",
      "Insignia",
      "Mokka",
      "Zafira",
      "Meriva",
      "Vectra",
      "Combo",
    ],
  },
  {
    name: "Dacia",
    logoFile: "dacia.webp",
    models: [
      "Sandero",
      "Duster",
      "Logan",
      "Jogger",
      "Spring",
      "Lodgy",
      "Dokker",
    ],
  },
  {
    name: "Tesla",
    logoFile: "tesla.webp",
    models: [
      "Model S",
      "Model 3",
      "Model X",
      "Model Y",
      "Cybertruck",
      "Roadster",
    ],
  },
  {
    name: "Citroën",
    logoFile: "citroen.jpg",
    models: [
      "C1",
      "C3",
      "C4",
      "C5 Aircross",
      "Berlingo",
      "DS3",
      "C4 Picasso",
      "C5 X",
    ],
  },
  {
    name: "Jeep",
    logoFile: "jeep.png",
    models: ["Renegade", "Compass", "Cherokee", "Wrangler", "Grand Cherokee"],
  },
  {
    name: "Mitsubishi",
    logoFile: "mitsubishi.jpg",
    models: ["Lancer", "Outlander", "ASX", "Pajero", "Eclipse Cross"],
  },
  {
    name: "Land Rover",
    logoFile: "landrover.jpg",
    models: ["Defender", "Discovery", "Range Rover", "Evoque", "Freelander"],
  },
  {
    name: "Subaru",
    logoFile: "subaru.png",
    models: ["Impreza", "Forester", "Outback", "Legacy", "XV", "BRZ"],
  },
  {
    name: "Seat",
    logoFile: "seat.jpg",
    models: ["Ibiza", "Leon", "Ateca", "Arona", "Toledo", "Altea"],
  },
  {
    name: "Mini",
    logoFile: "mini.png",
    models: [
      "Hatch",
      "Clubman",
      "Countryman",
      "Convertible",
      "John Cooper Works",
    ],
  },
  {
    name: "Alfa Romeo",
    logoFile: "alfa.png",
    models: ["Giulietta", "Giulia", "Stelvio", "Mito", "159"],
  },
  {
    name: "Suzuki",
    logoFile: "suzuki.png",
    models: ["Swift", "Vitara", "SX4", "Ignis", "Baleno", "Jimny"],
  },
  {
    name: "Chrysler",
    logoFile: "chrysler.png",
    models: ["300C", "Pacifica", "Voyager", "Sebring"],
  },
];
